addons:
  apt:
    packages:
      - python-dev
      - libssl-dev

language: python
sudo: false
cache: pip

python:
  - '2.7'

env:

  matrix:
  # TODO este test no funciona ya que pre-instala l10n_ar_invoice y al querer
  # hacerle init da error por actualizar periodo con movimientos
  # - TESTS="1" ODOO_REPO="odoo/odoo"
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:

  # TODO change to 8.0 when ready
  - git clone https://github.com/bmya/odoo-addons.git ${HOME}/odoo-addons -b ${VERSION}

  # oca account-financial-tools
  - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/account-financial-tools -b ${VERSION}

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success